language: java
jdk:
  - openjdk8
env:
  global:
  - CC_TEST_REPORTER_ID=a13279b52aa1feb62af3c8de23e825023d78576f182ed30168365510135f3712
  - secure: Fr1DNZq3f5AkQpbFUmu95eyEXUEF467KWATfq/PZmA/EYCRbglRxV/Go7zd2Xoub2OcPVUHQcaRANmQvtiM8W40Rheyt36NTmyx/BYQFZojzclwg8+Oy9wUGkyfOzO9g18zV/QZAqq7vBf362S4+Zzlr3N38xm5gkSMmO1xnU/0N6GSzqsrQ9w7OYjAVGatK/5+KPEER52N6F/xv5/Db5DbJS4ViQZ7NpunNEuhu94lb1f7+73L5YqdfeQnwJXJXx5Y+eDhARHA23BbZQkMqsp25O+aRaeo1OTuKNF83Qs+Vev/flISFhbl/iCaAde9g/ZH9+1eTHJTmdIjBB9OFXPIW2dGrHiJSYD6XD0BqwjbLnMXN+VkBUqX45Pt363Ev3vhwNOQ06AmQwkojGPRmfDhAXL7GKfaBMFzqKmIQa0BKfZADL6Q+/29k+f8SpxTzbFPAuAeZr0UuaD+IbX5X/X/GNv/Ir8va965/at6+DfFPHja1p27BVLox1JvdYdM7f2JnoiLOasHjUdnoL8wIFrCEPUGLMznM2DXQZxkkuaBulRTnLlUwLBIEJ5623tc7VSeGmjD+9Uk6jfiB9Ulqt4s6fZuq4d+F0Azr6D6D/9ZpwG6xkEPfeVOjQdiqpIluyILhRaFbf21OQnwEdn5iteKRqIxBTJV1HEZuR4GgALc=
  - secure: Y65+h8WYPqYxuESDXlKE+RcrQAAA7LHjE+6gvXOsKVrPN89vlvduwbBgrz9nUPpi1nKeNIIx71/4FtzY4Thx02XewyXjT6KJEzX1m/CAIdER2O9R/SqMJqHS/ghqSf3nl2elrNtv0NQfjU9yBUEDe1zzj2UfNoinkkJVq8pe2Q0In8y15FxvOfbCngK/rKc3w6TMowBdE90gQlHPgZotSJ9XVcgtusY+L583CYJGgPQBoyZyugoQOmuRok1EkJTOuy+YZzft3ehAHDubjdgqTarmvD8GX0ReMH1WndeLIt54sd3+iQJ3olYD1AybOr0PKCsPbeVxTyZXdWFpyDbXcPM600A+E6Jstg85HohCqKh6VcqSKDCTe5OB0r5ERVIZlL6VVn6g6BKCzZ4y59yIW+OrwfKrJ4ycR+BCsDrtDSFq7qEOGG3j+aU2gFmqlGrEDxhnQK4gCdXCCq5/odSSOEj30Bl2pNVDpleli/WeihaRl77VhEnWpAdNYb4om5/4UlV52Y121mwO6qVmC2BgEPeLBAYwas/FI//JwoTAAqEUms5XC5nsGJUERA6NqQ6p/0E/pZ3UTtavX3dYpAhcuyn/wy2TEcc7xUOxcteqGdee33nlgNyGp8zTjV7dcpaBoRbl6N6vwgXjgslyHk/iSt/K6NwI5AP3sTV2c4jSG6c=
  - secure: RaHQcFWEtdUjk0zy/SfcqKDxt4CKDwG6OQA2pADAeelSg9+qkHJ0g39lm252hpxKQbLckqoyKcBawsTjQKv/qu1CXnTrZVJms95mQ2groRFvcxRPMtHggfi8rPQSeWUKh9wzzR+LhBhK7Bhh3z7MAkvTAmBi2haCtvM3wyThAqHHbMP1WXZs+oF6xt9tfEXUXJEzEJKL/+LkW8sLJSHtXq4bczi6+FdsOHYHvAg9uxqUfLE5tgSEZcLKuESyTtodfGUlrOljRntNxkx+Y5FgdxWBk0k3aI21G+9J51EzQAxza2GQRdJERsunVt9uyIQ9LINkOUgC13BsnKT/8T4Jtr1HMAYJVVyZ4liASMkonHG5jybnVwCO7Szg7P3zieSyhmVVD7tcQsg4WWmGhnc6/qLTUK3JHTJ56a8IKpVzjwbc94aCFeFB4rInymrJ2tVapZ3ix3ieV6R/R4K8OkKLl6nMs4qvPS0yXegDI5yFa2fnexNALuntr3uCaJszaRDB/kefAtcsOn1U1fJCm+aIvvAoIasCandUDTzQScoSYJ6/P9FjmHNPS8pELVMnFfNl1kWm0FvlLYPuPqnXU8OgIiNmY34ikxAvTJgE9K/tnJrPwhH2q2wg8R5Jmqe5ikhHUOBp4k4sNC0j4oTAziCK8c7gIJ7008jfv2C3ToKptyk=
install:
- mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true
  -B -V
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- ".travis/before-script.sh"
script:
- mvn test
- "./cc-test-reporter format-coverage -d -t jacoco ./target/jacoco-ut/jacoco.xml"
- "./cc-test-reporter upload-coverage -d"
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
- provider: script
  script: ".travis/deploy.sh"
  skip_cleanup: true
  on:
    repo: trickl/oanda-java-client
    all_branches: true
- provider: releases
  skip_cleanup: true
  api_key:
    secure: I2yiS+EmdMJfQRTDS7n8OOz+/hFC8NpjVGPnAYI4o4TkuTE6t+M0pa7nHCMmE7amfUgx3rhgu8PFj482nlpr6F4yS/9C2M6gCElusv5GcO067XATx4TYfiMdPKze8900pR4nPs35d9ln7OGfPiehuG8zIXCNMNzXN5G+h+doTrdLCynOR1eAj+0iiSx+rkAnobJEHSllNIfzjlqyLVAiGhh13hIrBb6Pw0SvbtzEyc9d895scsX1LXm6D/nsttF+R+unkygDPXnokhIVEFwSiO5ilWCoQpzPZt8Ut9UGN6ZqKYM1IWzJmn1pHnbZGxJtDw9YR3i2blrzjRthuKy7r8QbI6QeszorT2xA+zOxvu+xNgSbmS7N9UXjnHC+k3F5z9B4blrZ4vk2UQExOXWS2pNjIVFKO65DvjeC8kS5k7bNj7DXBm9MLMimLY1vkz5JlOKgCndzZijw/EqCApXylsZma/WfQvXrllynEP+O7x59jjn+U8Tj8PMuwqThCJiPpuvHhZptC0b6gVDvUdI8eHvBDl2YOYbIdC3Ddc9+4U8/AgROJwLrPbhcQhRh+toc8j1fFdKVKld4Hq/sbs9sGOuqgpNI1urzJqhCUEH04p2YJrbbQyznweXAY5FD6lInG49d7cnHWzKnXAK9TqVDFUR8A5S2cU9SVFRErUJpA4s=
  file: ".travis.yml"
  on:
    repo: trickl/oanda-java-client
